
services:
  xiidea.easy_audit.doctrine_subscriber:
          class: Xiidea\EasyAuditBundle\Subscriber\DoctrineSubscriber
          arguments: ['%xiidea.easy_audit.doctrine_objects%']
          calls:
              - [ setDispatcher,[ '@event_dispatcher' ] ]
          tags:
              - { name: doctrine.event_listener, event: preRemove }
              - { name: doctrine.event_listener, event: postUpdate }
              - { name: doctrine.event_listener, event: postRemove }
              - { name: doctrine.event_listener, event: postPersist }
              - { name: doctrine_mongodb.odm.event_listener, event: preRemove }
              - { name: doctrine_mongodb.odm.event_listener, event: postUpdate }
              - { name: doctrine_mongodb.odm.event_listener, event: postRemove }
              - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
